services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ask.org.az-sqlserver
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - ask-network


  api:
    build:
      context: .
      dockerfile:  src/App.API/Dockerfile   # <-- project-root içində Dockerfile yeri
    container_name: api.ask.org.az
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    networks:
      - ask-network

networks:
  ask-network:
    driver: bridge