name: Deploy API

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u nihadrasulzada --password-stdin

      - name: Build Image
        run: |
          docker build -t ghcr.io/nihadrasulzada/ask-api:latest -f src/App.API/Dockerfile src

      - name: Push Image
        run: docker push ghcr.io/nihadrasulzada/ask-api:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to server
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22

          script: |
            cd /home/app
            docker compose pull
            docker compose up -d